export const CONNECT_SLACK_SUCCESS = "CONNECT_SLACK_SUCCESS";
export const CONNECT_SLACK_FAILURE = "CONNECT_SLACK_FAILURE";
export const INITIALIZE_SLACK = "INITIALIZE_SLACK";
export const DISCONNECT_SLACK_SUCCESS = "DISCONNECT_SLACK_SUCCESS";
export const DISCONNECT_SLACK_FAILURE = "DISCONNECT_SLACK_FAILURE";