version: '3.8'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - /var/www/maraca:/usr/src/app/dist
    ports:
      - "3000:3000"
    command: yarn dev