export const CONNECT_WEBSOCKET = 'CONNECT_WEBSOCKET';
export const DISCONNECT_WEBSOCKET = 'DISCONNECT_WEBSOCKET';
export const WEBSOCKET_CONNECTED = 'WEBSOCKET_CONNECTED';
export const WEBSOCKET_DISCONNECTED = 'WEBSOCKET_DISCONNECTED';
export const WEBSOCKET_ERROR = 'WEBSOCKET_ERROR';
export const START_RECORDING = 'START_RECORDING';
export const STOP_RECORDING = 'STOP_RECORDING';
export const AUDIO_DATA_AVAILABLE = 'AUDIO_DATA_AVAILABLE';
export const EXIT_CONVERSATION = 'EXIT_CONVERSATION';
export const SEND_AUDIO_DATA = 'SEND_AUDIO_DATA';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';
export const RESET_AUDIO_DATA = 'RESET_AUDIO_DATA';

export const SERVER_CONFIRMED_EXIT = 'SERVER_CONFIRMED_EXIT';
export const WEBSOCKET_SHOULD_CLOSE = 'WEBSOCKET_SHOULD_CLOSE';

export const SEND_TRANSCRIPT_DATA = 'SEND_TRANSCRIPT_DATA';
export const SEND_AUDIO_BLOB = 'SEND_AUDIO_BLOB';
// ... other action types as needed
