// actionTypes.js
export const SUBMIT_ONBOARDING_FORM = 'SUBMIT_ONBOARDING_FORM';
export const ONBOARDING_FORM_SUCCESS = 'ONBOARDING_FORM_SUCCESS';
export const ONBOARDING_FORM_FAILURE = 'ONBOARDING_FORM_FAILURE';
// actionTypes.js
export const RESET_ONBOARDING_FORM = 'RESET_ONBOARDING_FORM';
