export const CONNECT_SALESFORCE_SUCCESS = "CONNECT_SALESFORCE_SUCCESS";
export const CONNECT_SALESFORCE_FAILURE = "CONNECT_SALESFORCE_FAILURE";
export const INITIALIZE_SALESFORCE = "INITIALIZE_SALESFORCE";
export const DISCONNECT_SALESFORCE_SUCCESS = "DISCONNECT_SALESFORCE_SUCCESS";
export const DISCONNECT_SALESFORCE_FAILURE = "DISCONNECT_SALESFORCE_FAILURE";