export const FETCH_SALES_SCENARIO_REQUEST = 'FETCH_SALES_SCENARIO_REQUEST';
export const FETCH_SALES_SCENARIO_SUCCESS = 'FETCH_SALES_SCENARIO_SUCCESS';
export const FETCH_SALES_SCENARIO_FAILURE = 'FETCH_SALES_SCENARIO_FAILURE';
